"use client"
const PrivacyPolicy = () => {
    return (
        <>
            <section className="h-auto p-5 bg-slate-100 dark:bg-slate-800 text-black dark:text-white text-justify">
                <div className="main-title p-5">
                    <h1 className="font-bold text-3xl">Privacy & Policy</h1>
                </div>
                <div className="detail p-5">
                    <span className="pt-2">Last updated : January 01, 2024 <br/></span>

                    <p className="pt-4">
                    This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                    
                    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                    </p>

                    <h1 className="pt-5 text-3xl font-bold text-green-500">Interpretation and Definitions</h1>
                    <h2 className="pt-2 text-green-500 font-bold text-2xl">Interpretation</h2>
                    <p className="pt-3">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

                    <h2 className="pt-2 text-green-500 font-bold text-2xl">Definitions</h2>
                    <p className="pt-3">For the purposes of this Privacy Policy:</p>

                    <ul className="list-disc p-2">
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Account</span> means a unique account created for You to access our Service or parts of our Service.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Affiliate</span> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Company</span> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to SportsBuddy, Thane , Mumbai.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Cookies</span>  are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Country</span> refers to: Maharashtra, India.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Device</span> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Personal Data</span> is any information that relates to an identified or identifiable individual.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Service</span> refers to the Website.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                        </li>
                    </ul>

                    <h1 className="pt-4 text-green-500 font-bold text-4xl">Collecting and Using Your Personal Data</h1>
                    <h2 className="pt-2 text-green-500 font-bold text-3xl">Types of Data Collected</h2>
                    <h2 className="pt-2 text-green-500 font-bold text-2xl">Personal Data</h2>

                    <p className="pt-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>

                    <ul className="list-disc">
                        <li className="pt-1">Email address</li>
                        <li className="pt-1">First name and last name</li>
                        <li className="pt-1">Phone number</li>
                        <li className="pt-1">Address, State, Province, ZIP/Postal code, City</li>
                        <li className="pt-1">Usage Data</li>
                    </ul>

                    <h2 className="pt-2 text-green-500 font-bold text-2xl">Usage Data</h2>

                    <p className="pt-2">
                    Usage Data is collected automatically when using the Service.<br/><br/>

                    Usage Data may include information such as Your Devices Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.<br/><br/>

                    When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.<br/><br/>

                    We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                    </p>

                    <h2 className="pt-2 text-green-500 font-bold text-2xl">Tracking Technologies and Cookies</h2>
                    <p className="pt-2">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>

                    <ul className="list-disc">
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Cookies or Browser Cookies :</span>
                            <p className="pt-2">A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</p>
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Web Beacons :</span>
                            <p className="pt-2">Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</p>
                        </li>
                    </ul>
                    <p className="pt-2">
                    Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.<br/><br/>
                    We use both Session and Persistent Cookies for the purposes set out below:
                    </p>

                    <ul className="list-disc">
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Necessary / Essential Cookies :</span>
                            <p className="pt-2">
                                Type: Session Cookies<br/>
                                Administered by: Us<br/>
                                Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                            </p>
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Cookies Policy / Notice Acceptance Cookies :</span>
                            <p className="pt-2">
                                Type: Persistent Cookies<br/>
                                Administered by: Us<br/>
                                Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
                            </p>
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">Functionality Cookies : </span>
                            <p className="pt-2">
                                Type: Persistent Cookies<br/>
                                Administered by: Us<br/>
                                Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
                            </p>
                        </li>
                    </ul>
                    <p className="pt-4">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

                    <h2 className="pt-2 text-green-500 font-bold text-2xl">Use of Your Personal Data</h2>

                    <p className="pt-2">The Company may use Personal Data for the following purposes:</p>

                    <ul className="list-disc">
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">To provide and maintain our Service</span> , including to monitor the usage of our Service.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">To manage Your Account :</span> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">For the performance of a contract :</span> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">To contact You :</span>  To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile applications push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">To provide You</span> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">To manage Your requests :</span> To attend and manage Your requests to Us.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">For business transfers :</span> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">For other purposes:</span> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
                        </li>
                    </ul><br/><br></br>
                    We may share Your personal information in the following situations:<br/><br/>

                    <ul className="list-disc">
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">With Service Providers :</span>
                            <p className="pt-2">
                                We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
                            </p>
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">With Affiliates :</span>
                            <p className="pt-2">
                                We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
                            </p>
                        </li>
                        <li className="pt-2">
                            <span className="text-green-500 font-bold">With business partners :</span>
                            <p className="pt-2">
                                We may share Your information with Our business partners to offer You certain products, services or promotions.
                            </p>
                        </li>
                    </ul>

                    <h2 className="pt-2 text-green-500 font-bold text-2xl">Retention of Your Personal Data</h2>
                    <p className="pt-2">
                    The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.<br/><br/>
                    The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
                    </p>

                    <h2 className="pt-2 text-green-500 font-bold text-2xl">Transfer of Your Personal Data</h2>
                    <p className="pt-2">
                        Your information, including Personal Data, is processed at the Companies operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.<br/><br/>

                        Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.<br/><br/>

                        The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.<br/><br/>
                    </p>

                    <h2 className="pt-2 text-green-500 font-bold text-2xl">Delete Your Personal Data</h2>
                    <p className="pt-2">
                        You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.<br/><br/>

                        Our Service may give You the ability to delete certain information about You from within the Service.<br/><br/>

                        You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.<br/><br/>

                        Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.<br/><br/>
                    </p>

                    <h2 className="pt-2 text-green-500 font-bold text-2xl">Disclosure of Your Personal Data</h2>
                    <h3 className="pt-2 text-green-500 font-bold text-xl">Business Transactions :</h3>
                    <p className="pt-2 ">
                        If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                    </p>

                    <h3 className="pt-2 text-green-500 font-bold text-xl">Law enforcement :</h3>
                    <p className="pt-2 ">
                        Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                    </p>

                    <h3 className="pt-2 text-green-500 font-bold text-xl">Other legal requirements :</h3>
                    <p className="pt-2 ">
                        The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:<br/><br/>

                        <ul className="list-disc">
                            <li className="pt-2">Comply with a legal obligation</li>
                            <li className="pt-2">Protect and defend the rights or property of the Company</li>
                            <li className="pt-2">Prevent or investigate possible wrongdoing in connection with the Service</li>
                            <li className="pt-2">Protect the personal safety of Users of the Service or the public</li>
                            <li className="pt-2">Protect against legal liability</li>
                        </ul>
                    </p>

                    <h3 className="pt-2 text-green-500 font-bold text-2xl">Security of Your Personal Data</h3>
                    <p className="pt-2">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

                    <h3 className="pt-2 text-green-500 font-bold text-2xl">Changes to this Privacy Policy</h3>
                    <p className="pt-2">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.<br/><br/>

                    We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.<br/><br/>

                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

                    <h3 className="pt-2 text-green-500 font-bold text-2xl">Changes to this Privacy Policy</h3>
                    <p className="pt-2">If you have any questions about this Privacy Policy, You can contact us: <br/>By Email : privacy@sportsbuddyweb.vercel.app</p>
                </div>
            </section>
        </>
    )
}
export default PrivacyPolicy